#### Prokaryotic Annotation Config ####
# NOTE: If --assembly-file is not used, the pipeline will automatically search for assemblies from India.

# Query for the organism in NCBI databases
organism: "Mycobacterium tuberculosis "

# URLs for reference data
reference_genome_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/195/955/GCF_000195955.2_ASM19595v2/GCF_000195955.2_ASM19595v2_genomic.fna.gz"
gff_url: "https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/195/955/GCF_000195955.2_ASM19595v2/GCF_000195955.2_ASM19595v2_genomic.gff.gz"

# Email address for NCBI notifications
email: "your@email.com"

# NCBI taxonomic group
group: "bacteria"

# Organism type: Set to PK for Prokaryotic
organism_type: "PK"

# QUAST parameters
quast_threads: 8

# BUSCO parameters
busco_lineage: "bacteria_odb10"
busco_params:
  cpu: 8

location: "India"

# Parameters for Prokaryotic Genome Annotation (Prokka)
prokka_kingdom: "Bacteria"
prokka_env: "assembly_tool_env"
prokka_params:
  cpus: 8


# Optional empty sections
quast_params: {}
prokka_params: {}
